### ISSUE TITLE
Meeting: Code review and software engineering

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/flow-update#2]

**Comment by postfalk** [comment]
@kklausmeyer Please setup meeting. I think we should take at least 2 hours and maybe maximum 2 hours at a time. I did not address how Jupyter notebook would come in here since this would be more a workflow and documentation problem.

**Comment by kklausmeyer** [comment]
Done- friday 3/22 @9:30am scheduled in outlook.
